### ISSUE TITLE
Admin2 Suffix

### ISSUE THREAD

**Issue by missinglink** [pelias/quattroshapes#24]
```bash
    {
      "type": "Feature",
      "properties": {
        "id": "39538:locality:be:bel:brussel",
        "layer": "locality",
        "name": "Brussel",
        "alpha3": "BEL",
        "admin0": "Belgium",
        "admin2": "Brussel-Hoofstad#Bruxelles-Capitale",
        "text": "Brussel, Brussel-Hoofstad#Bruxelles-Capitale, Belgium"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          4.37345158212375,
          50.8384796702664
        ]
      }
    },
```

**Comment by nvkelso** [comment]
The # is a separate between language names (Brussel-Hoofstad and Bruxelles-Capitale)

**Comment by missinglink** [comment]
The actionable here is to search for and split on the `#` character and import both names, in lieu of language keys let's just say the first one maps to `name.default` in pelias and the others map to `name.alt1` etc.

**Comment by missinglink** [comment]
For Sweden we will need to probably import `qs_adm0` as the 'main` english name but also `qs_a0` as the Swedish name cc/ @nvkelso

```javascript
{
  "type": "Feature",
  "properties": {
    "qs_adm0_a3": "SWE",
    "qs_adm0": "Sweden",
    "qs_level": "adm0",
    "qs_iso_cc": "SE",
    "qs_a0": "Sverige",
    "qs_a0_alt": "Sverige",
    "qs_a0_lc": "SE0000",
    "qs_source": "EuroGlobalMap",
    "qs_pop": null,
    "qs_id": null,
    "qs_gn_id": null,
    "qs_woe_id": null,
    "qs_scale": null,
    "quad_count": 17919,
    "photo_sum": 620170,
    "photo_max": 121764,
    "localhoods": 96969,
    "local_sum": 119403432,
    "local_max": 15300552,
    "popularity": 620170,
    "lat": 62.3599815259509,
    "lon": 16.9122043617686
  },
  "geometry": [<<<truncated>>>]
}
```

**Comment by riordan** [comment]
Sounds like we're just going to solve this when we move from Quattroshapes to Who's on First.

**Comment by nvkelso** [comment]
Agree that makes the most sense.

**Comment by riordan** [comment]
@thisisaaronland Is Who's on First still using "language separators#séparateurs linguistiques" for multilingual countries?

**Comment by thisisaaronland** [comment]
I am not sure I understand the question but if it is:

"Does Who's On First encode multiple language names for a place type in a single string?"

Then the answer is:

"Only as a by-product of a past import and those records will be updated to follow the conventions for naming things. [1]"

Does that answer your question?

[1] https://github.com/whosonfirst/whosonfirst-names

**Comment by riordan** [comment]
That sure does answer the question.


On 1/27/16 15:55, Aaron Straup Cope wrote:
> I am not sure I understand the question but if it is:
>
> "Does Who's On First encode multiple language names for a place type in
> a single string?"
>
> Then the answer is:
>
> "Only as a by-product of a past import and those records will be updated
> to follow the conventions for naming things. [1]"
>
> Does that answer your question?
>
> [1] https://github.com/whosonfirst/whosonfirst-names
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/quattroshapes/issues/24#issuecomment-175848564>.
>

-- 
David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | gpg 235D 9DC9 5EF6 277C
@riordan | +1 (203)-521-1222
https://mapzen.com | @mapzen

**Comment by dianashk** [comment]
Fixed by WOF, but should be resolved in QS

**Comment by nvkelso** [comment]
**Side note:** QS is no longer maintained, the WOF fixes won't be back ported.

**Comment by dianashk** [comment]
@nvkelso, sorry the last comment wasn't very clearly worded. I meant that it would still need to be resolved in QS manually in the future.

**Comment by riordan** [comment]
Issue still present in WoF ([record](https://whosonfirst.mapzen.com/spelunker/id/102049957/)).

Should be resolved with concordance + WoE words import.

**Comment by thisisaaronland** [comment]
Is there an open ticket or pull request (in WOF-space) that I've simply managed to space on?

**Comment by nvkelso** [comment]
I think there was a ticket to change the locality (which was done), but
turns out more same-named elements in the hierarchy also need updating?

On Tue, Apr 5, 2016 at 12:38 PM, Aaron Straup Cope <notifications@github.com

**Comment by orangejulius** [comment]
While we don't import Quattroshapes directly any more, this is still an issue that has been brought into WOF: http://pelias.github.io/compare/#/v1/search%3Ftext=Brussel-Hoofstad

**Comment by trescube** [comment]
Move issue to pelias/pelias
